services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Services\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50

    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Services\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments :
            - "@oc_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }
